# Generated by Django 3.2.18 on 2023-09-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_faq'),
    ]

    operations = [
    ]
