# Generated by Django 3.2.18 on 2023-09-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bullyingreport'),
        ('myapp', '0004_merge_0002_faq_0003_auto_20230923_2129'),
    ]

    operations = [
    ]
